#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/hypr/config/monitors.lua"

# Disable DP-1, Enable HDMI-A-1
sed -i '/output = "DP-1"/,/disabled =/ s/disabled = false/disabled = true/' "$CONFIG_FILE"
sed -i '/output = "HDMI-A-1"/,/disabled =/ s/disabled = false/disabled = false/' "$CONFIG_FILE"

# Reload Hyprland config
hyprctl reload
